export const SCREENS = {
    Signup: "SignupScreen",
    Login: "LoginScreen",
    SelectSchool: "SelectSchoolScreen",
    IntroduceEvents: "IntroduceEventsScreen",
    TabNavigator: "TabNavigator",
    ExploreEvents: "ExploreEventsScreen",
    Search: "SearchScreen",
    MyCalendar: "MyCalendarScreen",
    MyProfile: "MyProfileScreen",
    EventDetails: "EventDetailsScreen",
    EditEvent: "EditEventScreen",
    ProfileDetails: "ProfileDetailsScreen",
    CreateEvent: "CreateEventScreen",
    PreviewEvent: "PreviewEventScreen",
    EditProfile: "EditProfileScreen",
    Settings: "SettingsScreen",
    EditMyPassword: "EditMyPasswordScreen",
    AccountSettings: "AccountSettingsScreen",
    Home: "HomeScreen",
    AccountFollowList: "AccountFollowListScreen",
    Onboarding: {
        SignupWelcomeScreen: "SignupWelcomeScreen",
        SignupSchoolScreen: "SignupSchoolScreen",
        SignupNameScreen: "SignupNameScreen",
        SignupUsernameScreen: "SignupUsernameScreen",
        SignupEmailScreen: "SignupEmailScreen",
        SignupPasswordScreen: "SignupPasswordScreen",
        SignupFinalScreen: "SignupFinalScreen",
    },
    NotificationsSettings: "NotificationSettings"
}